### ISSUE TITLE
백그라운드에서만 동작이 감지된다는 것을 알리는 뷰 추가하기

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#103]
## Description

유저에게 흔들기 동작이 백그라운드 상태에서만 동작한다늘 것을 알리기 위헤 이미지 뷰를 추가한다.

## To-do

- [x] 이미지 추가
- [x] 뷰에 이미지 추가
- [x] 뷰에 닫기 버튼 추가
- [ ] 이미지에서 다시 보지 않기를 누르면 다시는 보이지 않게 하기
