### ISSUE TITLE
맞춤 랜덤 선곡 기능 구현

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#11]
## Description

맞춤 랜덤 선곡 섹션에 넣어줄 음악 데이터를 받아오는 모델을 구현합니다.

## To-do

- [x] MusicKit을 이용하여 개인 음악 추천 데이터 받기
- [x] 데이터를 사용할 수 있는 모델 만들기
- [x] 해당 모델을 사용하는 뷰의 프로퍼티 타입 수정해주기

## ETC (참고 자료)
https://developer.apple.com/documentation/musickit/musicpersonalrecommendationsrequest
