### ISSUE TITLE
흔드는 제스처 교체

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#119]
## Description

기존 책상에서 흔들기 방식 말고 기기를 들고 흔드는 방식으로 교체하기

## To-do

- [ ] ~~UIEvent를 이용해서 흔드는 모션 감지하기 (해당 방식은 background 상태에서 감지 불가)~~
- [ ] 바닥에 둔 상태를 감지하는 코드 삭제하기
- [ ] 기존 설정되어 있던 임계값을 기기를 들고 흔드는 상황에 맞춰 수정하기
- [ ] 감지되었을 때 음악 교체하기
