### ISSUE TITLE
장르별 노래 데이터 받아오기

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#122]
## Description

화면 개편에 따라, 홈화면에서 장르 선택이 가능하다.
선택한 장르에 따라 20곡 정도 추천 곡이 뜬다.
한 곡을 선택하면 그와 관련있는 곡들로 플레이리스트가 구성된다.

## To-do

- [ ] MusicKit에서 제공하는 장르 파악하기
- [ ] 장르로 노래 검색 가능한지 파악하기
- [ ] 장르에 따라 노래 데이터 요청하고 받아오는 작업하기
- [ ] 추후 다른 팀원의 view 작업이 끝나면 데이터 연결하기
