### ISSUE TITLE
OnboardingUserTutorial View, 3D Image, shake motion 추가하기

### ISSUE THREAD

**Issue by sun0e** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#26]
## Description

OnboardingUserTutorial View, 3D Image, shake motion 추가합니다.

## To-do

- [ ] OnboardingUserTutorial View 추가하기
- [ ] OnboardingUserTutorial 3D Image 추가하기
- [ ] OnboardingUserTutorial shake motion 추가하기
