### ISSUE TITLE
온보딩 화면 재구성, 페이지 인디케이터 위치 수정, 버튼 뷰 스와이프 X

### ISSUE THREAD

**Issue by Kimajun0919** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#38]
## Description

온보딩 화면(Tabview->custom) : 스와이프와 버튼 별도 구성 시 필요
페이지 인디케이터(페이지바뀌는거 확인하는거) 위치 변경(기존(가운데)->변경(하단))
버튼 뷰 시 스와이프 막고, 버튼으로 페이지 변경

## To-do

- [x] 온보딩 화면(Tabview->custom) 재구성
- [x] 페이지 인디케이터 위치 변경
- [x] 버튼 뷰 시 스와이프 막고, 버튼으로 페이지 변경 기능 추가
