### ISSUE TITLE
첫 곡 선곡하고 재생 리스트 구성하기

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#52]
## Description

사용자가 검색 혹은 홈 화면에서 개별곡 재생을 누른 이후 그 뒤에 이어질 재생 리스트를 구성할 예정입니다.

## To-do

- [ ] personal recommendation(made by 호랑)으로 트랙 리스트 받아오기
- [ ] 받아온 트랙 리스트를 Queue에 넣어주기
- [ ] 재생 리스트대로 잘 재생되는지 테스트하기
- [ ] 앨범 전체 재생 액션 추가하기
