### ISSUE TITLE
Create User Shake Action Detect Model

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#6]
## Description

Core Motion을 사용하여 사용자가 기기를 바닥에 엎어둔 상태에서 흔드는 것을 감지하는 모델을 만들고자 한다.

## To-do

- [x] Core Motion 권한 받기
- [x] 기기가 엎어져 있는 상태 감지하기
- [x] 유저가 기기를 흔드는 순간 감지하기
