### ISSUE TITLE
User Test 이후 피드백 사항

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#87]
## Description

유저 테스트 진행 후 받은 피드백 사항 반영

## To-do

- [x] 앨범 전체 재생 눌렀을 때 play 버튼 -> pause 버튼
- [x] 검색 결과 화면에서도 mini player view 띄우기
- [x] 다크 모드 색상 적용
- [x] 앨범 디테일 뷰에 네비게이션 타이틀 넣기
- [x] 화면이 위로 있는 상태에서도 흔들기 모션 감지
- [x] 온보딩 뷰 계속 보이게 설정하기 (for 부스 체험)
