### ISSUE TITLE
음악 재생 코드를 어디에 작성해야 할까?

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MC2-A3-BlackDragonRiver#96]
## Description

현재 음악 재생 관련 메서드를 Cell View에서 실행시키고 있는데, 이것이 최선의 방법인지에 대해 의문이 듭니다. 각 계층의 역할과 책임을 고려하여 음악 재생 메서드를 어디에 작성하는 것이 적절한지 논의가 필요합니다.

## To-do

- [ ] Cell, Row View, Home View 중 어디에서 음악 재생 메서드를 실행시켜야 할지 고민
- [ ] 각 계층의 역할과 책임 정리
- [ ] 관련 코드 수정 및 테스트
